# Generated by Django 3.0.5 on 2020-04-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=models.CharField(default='product_{<built-in function id>}', max_length=120)),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='product_{<built-in function id>}', max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=29.99, max_digits=100),
        ),
    ]
