# Generated by Django 3.0.5 on 2020-04-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('size', 'size'), ('colour', 'colour')], default='size', max_length=100),
        ),
    ]
