# Generated by Django 3.0.5 on 2020-04-25 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_colour_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colour',
            name='title',
        ),
        migrations.RemoveField(
            model_name='size',
            name='title',
        ),
    ]
