# Generated by Django 4.0.6 on 2022-07-25 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_coupon_product_stock_levels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
