# Generated by Django 3.0.5 on 2020-04-25 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_remove_cartitem_variations'),
        ('product', '0007_auto_20200425_1354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
