# Generated by Django 3.0.8 on 2020-07-05 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_auto_20200705_2042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdefaultaddress',
            options={'ordering': ['-updated', '-timestamp']},
        ),
        migrations.RemoveField(
            model_name='userdefaultaddress',
            name='billing',
        ),
        migrations.RemoveField(
            model_name='userdefaultaddress',
            name='shipping',
        ),
        migrations.AddField(
            model_name='userdefaultaddress',
            name='address',
            field=models.CharField(default='1', max_length=120),
        ),
        migrations.AddField(
            model_name='userdefaultaddress',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='userdefaultaddress',
            name='county',
            field=models.CharField(default='1', max_length=120),
        ),
        migrations.AddField(
            model_name='userdefaultaddress',
            name='phone_number',
            field=models.CharField(default='1', max_length=120),
        ),
        migrations.AddField(
            model_name='userdefaultaddress',
            name='postal_code',
            field=models.CharField(default='1', max_length=120),
        ),
        migrations.AddField(
            model_name='userdefaultaddress',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userdefaultaddress',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdefaultaddress',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
