# Generated by Django 3.0.8 on 2020-07-07 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200705_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdefaultaddress',
            options={},
        ),
        migrations.DeleteModel(
            name='UserStripe',
        ),
    ]
