# Generated by Django 3.0.5 on 2020-04-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_variation_category'),
        ('cart', '0009_auto_20200420_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, null=True, to='product.Variation'),
        ),
    ]
