# Generated by Django 3.0.5 on 2020-04-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_colour_size'),
        ('cart', '0010_cartitem_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='colours',
            field=models.ManyToManyField(blank=True, null=True, to='product.Colour'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='sizes',
            field=models.ManyToManyField(blank=True, null=True, to='product.Size'),
        ),
    ]
