# Generated by Django 3.0.8 on 2020-07-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default='1', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, default='1', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='1', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='1', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default='1', max_length=120),
        ),
    ]
