# Generated by Django 3.0.8 on 2020-07-05 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200704_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='order_id',
            new_name='order',
        ),
    ]
