# Generated by Django 3.0.8 on 2020-07-05 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200705_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='country',
            new_name='county',
        ),
    ]
