# Generated by Django 4.0.6 on 2022-07-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updated_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
    ]
