# Generated by Django 4.0.6 on 2022-07-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_updated_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='updated_total',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_used',
            field=models.BooleanField(default=False),
        ),
    ]
